import { Expert, Booking, Review } from "@/types";

export const mockExperts: Expert[] = [
  {
    id: "1",
    name: "Rahul Sharma",
    title: "SEBI-Licensed CA & Startup Advisor",
    bio: "10+ years helping Indian startups with taxation, GST, and fundraising compliance.",
    photo: "https://i.pravatar.cc/150?u=rahul",
    credentials: ["CA", "SEBI Registered", "B.Com"],
    rating: 4.9,
    sessions: 127,
    price: 500,
    availability: "Available Today",
    location: "Mumbai, India",
    responseTime: "Responds <2hr",
    isOnline: true,
    perMinuteRate: 15,
  },
  {
    id: "2",
    name: "Priya Patel",
    title: "Senior Product Designer at Google",
    bio: "Specializing in B2B SaaS UX design, portfolio reviews, and career transitions.",
    photo: "https://i.pravatar.cc/150?u=priya",
    credentials: ["Ex-Meta", "NID Alum"],
    rating: 5.0,
    sessions: 84,
    price: 1200,
    availability: "Next Available: Tomorrow",
    location: "Bangalore, India",
    responseTime: "Responds <1hr",
  },
  {
    id: "3",
    name: "Arjun Reddy",
    title: "Harvard MBA & Strategy Consultant",
    bio: "Former McKinsey consultant offering interview prep and GTM strategy advisory.",
    photo: "https://i.pravatar.cc/150?u=arjun",
    credentials: ["Harvard MBA", "Ex-McKinsey"],
    rating: 4.8,
    sessions: 215,
    price: 1500,
    availability: "Available Today",
    location: "New York, USA",
    responseTime: "Responds <4hr",
    isOnline: true,
    perMinuteRate: 25,
  },
  {
    id: "4",
    name: "Neha Gupta",
    title: "Staff Software Engineer",
    bio: "System design mock interviews and scalable backend architecture consulting.",
    photo: "https://i.pravatar.cc/150?u=neha",
    credentials: ["AWS Certified", "B.Tech IIT Delhi"],
    rating: 4.9,
    sessions: 56,
    price: 1000,
    availability: "Next Available: Wed",
    location: "Remote",
    responseTime: "Responds <1hr",
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    userId: "u1",
    userName: "Amit K.",
    rating: 5,
    date: "Oct 12, 2023",
    type: "Video Session",
    text: "Rahul was incredibly helpful in explaining the GST implications for my new SaaS product. Saved me hours of research!",
    verified: true,
  },
  {
    id: "r2",
    userId: "u2",
    userName: "Sneha V.",
    rating: 5,
    date: "Sep 28, 2023",
    type: "Chat Session",
    text: "Very clear and concise advice. Highly recommended.",
    verified: true,
  },
];

export const mockBookings: Booking[] = [
  {
    id: "b1",
    expertId: "1",
    expertName: "Rahul Sharma",
    expertPhoto: "https://i.pravatar.cc/150?u=rahul",
    date: "Nov 15, 2023",
    time: "10:00 AM",
    duration: "30 min",
    type: "video",
    price: 525,
    status: "upcoming",
  },
  {
    id: "b2",
    expertId: "2",
    expertName: "Priya Patel",
    expertPhoto: "https://i.pravatar.cc/150?u=priya",
    date: "Oct 05, 2023",
    time: "02:30 PM",
    duration: "45 min",
    type: "video",
    price: 1260,
    status: "completed",
  },
];
